// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2022.2.0f1";
    extern const char* const UnityVersionDigits = "2022.2.0";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 0;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.2.0f1_35dcd44975df";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.2.0f1_35dcd44975df";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.2.0f1 (35dcd44975df)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 3529940;

    extern const UInt64 UnityVersionDate = 1670257844;
    extern const char* const UnityVersionBranch = "2022.2/release";
    extern const char* const UnityVersionDisplay = "2022.2.0f1";
    extern const char* const UnityVersionDisplay_Verbose = "2022.2.0f1.112.6075";
    extern const char* const UnityVersionRevision = "35dcd44975df";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.2.0f1 (35dcd44975df)";
    extern const wchar_t* const L_UnityVersion = L"2022.2.0f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 0
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.2.0f1_35dcd44975df"
    #define UNITY_VERSION_PARENS_HASH "2022.2.0f1 (35dcd44975df)"
    #define UNITY_VERSION_BLD 3529940
    #define UNITY_VERSION_WIN "2022.2.0.3529940"

#endif // !RC_INVOKED
